#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

#./Allclean
#./Allrun.pre

runApplication decomposePar
runParallel $(getApplication) &


sleep 20

#gnuplot resPlot.txt -

#$(getApplication) -postProcess -func yPlus

#runApplication reconstructPar 

#------------------------------------------------------------------------------
